# vim:set ft=tmux:
%hidden MODULE_NAME="meetings"

set -ogq "@catppuccin_${MODULE_NAME}_icon" " "
set -ogqF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_blue}"
set -ogq "@catppuccin_${MODULE_NAME}_text" " #($TMUX_PLUGIN_MANAGER_PATH/catppuccin-tmux-neon/scripts/meetings.sh)"

source -F "#{d:current_file}/../utils/status_module.conf"
